name: 'Update Sphinx Translations'
description: 'GitHub Action to automatically update Sphinx translations from a source repository.'
author: 'Your Name <your-email@example.com>'
inputs:
  source_repo:
    description: 'The URL of the source repository to fetch translations from.'
    required: true
    default: 'https://github.com/your-org/source-repo.git'
  target_branch:
    description: 'The branch to push the updated translations to.'
    required: false
    default: 'main'
  languages:
    description: 'Comma-separated list of languages to update (e.g., en,fr,de).'
    required: true
    default: 'en'

runs:
  using: 'docker'
  image: 'docker://python:3.9'
  entrypoint: 'bash'

  # Command to run the update action
  args:
    - 'bash'
    - '-c'
    - |
        git clone --single-branch $INPUT_SOURCE_REPO /tmp/source-repo
        cd /tmp/source-repo
        git pull origin $GITHUB_REF

        cp -r /tmp/source-repo/docs/locale/* ./docs/locale/
        
        cd docs
        sphinx-intl update -p build -l $INPUT_LANGUAGES

        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add docs/locale
        git commit -m "Update translations from source repository"
        git push origin $INPUT_TARGET_BRANCH

outputs:
  updated_files:
    description: 'List of updated translation files'
