name: 'Example: Update Sphinx Translations'

on:
  push:
    branches:
      - main

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Update translations
      uses: flaskcwg/sphinx-translate-sync@v1
      with:
        source_repo: 'https://github.com/flaskcwg/flask-docs-es'
        target_branch: 'main'
        languages: 'en,fr,de'
